=== OpenEdition/bilbo/dependencies/PyXML-0.8.4/demo/quotes/quotations.dtd
<!-- 
     A DTD for storing simple quotations.  This DTD doesn't provide
     sophisticated cross-referencing or anything like that; if you're
     working on the next edition of Barlett's Familiar Quotations,
     you'll need a fancier DTD with more features.  

     Version 1.0 : Sep 5 1998
     A.M. Kuchling (amk1@bigfoot.com)
-->

<!ELEMENT quotations (quotation)*>

<!ELEMENT quotation (#PCDATA | em | foreign | cite | br | pre | code |
                     author | source)* >
<!ELEMENT author (#PCDATA)>
<!ELEMENT source (#PCDATA|cite)*>

<!-- Different forms of emphasis for phrases -->

<!ELEMENT cite (#PCDATA) >
<!ELEMENT code (#PCDATA) >
<!ELEMENT em (#PCDATA) >
<!ELEMENT foreign (#PCDATA) >
<!ELEMENT pre (#PCDATA) >
<!ATTLIST pre xml:space (default|preserve) 'preserve'>

<!-- Break element -->
<!ELEMENT br EMPTY>
 
<!-- Various accents -->

<!ENTITY acirc "&#226;">
<!ENTITY ccedil "&#231;">
<!ENTITY eacute "&#233;">
<!ENTITY iuml "&#239;">
<!ENTITY oacute "&#243;">
<!ENTITY ouml "&#246;">

=== OpenEdition/bilbo/dependencies/PyXML-0.8.4/demo/quotes/sample.xml
<?xml version="1.0"?>
<!DOCTYPE quotations SYSTEM "quotations.dtd">

<quotations>

<quotation>
We will perhaps eventually be writing only small modules which are
identified by name as they are used to build larger ones, so that
devices like indentation, rather than delimiters, might become
feasible for expressing local structure in the source language.

<source>Donald E. Knuth, "Structured Programming with goto
Statements", Computing Surveys, Vol 6 No 4, Dec. 1974</source>
</quotation>

<quotation>
I don't know a lot about this artificial life stuff
-- but I'm suspicious of anything Newsweek gets goofy about
-- and I suspect its primary use is as another money extraction tool
to be applied by ai labs to the department of defense
(and more power to 'em).
<br/>
Nevertheless in wondering why free software is so good these days
it occured to me that the propagation of free software is one gigantic
artificial life evolution experiment, but the metaphor isn't perfect.
<br/>
Programs are thrown out into the harsh environment, and the bad ones
die. The good ones adapt rapidly and become very robust in short
order.
<br/>
The only problem with the metaphor is that the process isn't random
at all. Python <em>chooses</em> to include tk's genes; Linux decides
to make itself more suitable for symbiosis with X, etcetera. 
<br/>
Free software is artificial life, but better.
<source>Aaron Watters, 29 Sep 1994</source>
</quotation>

<quotation>
It has also been referred to as the "Don Beaudry <em>hack</em>," but
that's a misnomer.  There's nothing hackish about it -- in fact,
it is rather elegant and deep, even though there's something dark
to it.
<source>Guido van Rossum, <cite>Metaclass Programming in Python 1.5</cite></source>
</quotation>

<quotation>
This is not a technical issue so much as a human issue; we 
are limited and so is our time.  (Is this a bug or a feature of time?
Careful; trick question!)
<source>Fred Drake on the Documentation SIG, 9 Sep 1998</source> 
</quotation>

<quotation>
Counting is the most simple and primitive of narratives -- 1 2 3 4 5 6
7 8 9 10 --  a tale with a beginning, a middle and an end and a sense
of progression -- arriving at a finish of two digits -- a goal
attained, a denouement reached.
<author>Peter Greenaway</author>
<source><cite>Fear of Drowning By Numbers</cite> (1988)</source>
</quotation>

</quotations>
