=== OpenEdition/bilbo/dependencies/PyXML-0.8.4/demo/dom/addr_book.dtd
<!ELEMENT ADDRBOOK ((ENTRY | ENTRY-LINK)*)>
<!ELEMENT ENTRY (NAME, ADDRESS, PHONENUM*, EMAIL)>
<!ATTLIST ENTRY
    ID ID #REQUIRED
>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT ADDRESS (#PCDATA)>
<!ELEMENT PHONENUM (#PCDATA)>
<!ATTLIST PHONENUM
    DESC CDATA #REQUIRED
>
<!ELEMENT EMAIL (#PCDATA)>
<!ELEMENT ENTRY-LINK EMPTY>
<!ATTLIST ENTRY-LINK
    xml:link (simple|extended|group) #REQUIRED
    href CDATA #REQUIRED
>

=== OpenEdition/bilbo/dependencies/PyXML-0.8.4/demo/dom/addr_book1.xml
<?xml version = "1.0"?>
<!DOCTYPE ADDRBOOK SYSTEM "addr_book.dtd">
<ADDRBOOK xmlns:xlink="http://www.w3.org/XML/XLink/0.9">
	<ENTRY ID="pa">
		<NAME>Pieter Aaron</NAME>
		<ADDRESS>404 Error Way</ADDRESS>
		<PHONENUM DESC="Work">404-555-1234</PHONENUM>
		<PHONENUM DESC="Fax">404-555-4321</PHONENUM>
		<PHONENUM DESC="Pager">404-555-5555</PHONENUM>
		<EMAIL>pieter.aaron@inter.net</EMAIL>
	</ENTRY>
	<ENTRY-LINK xlink:link="simple" xlink:href="addr_book2.xml"/>
	<ENTRY ID="en">
		<NAME>Emeka Ndubuisi</NAME>
		<ADDRESS>42 Spam Blvd</ADDRESS>
		<PHONENUM DESC="Work">767-555-7676</PHONENUM>
		<PHONENUM DESC="Fax">767-555-7642</PHONENUM>
		<PHONENUM DESC="Pager">800-SKY-PAGEx767676</PHONENUM>
		<EMAIL>endubuisi@spamtron.com</EMAIL>
	</ENTRY>
	<ENTRY ID="vz">
		<NAME>Vasia Zhugenev</NAME>
		<ADDRESS>2000 Disaster Plaza</ADDRESS>
		<PHONENUM DESC="Work">000-987-6543</PHONENUM>
		<PHONENUM DESC="Cell">000-000-0000</PHONENUM>
		<EMAIL>vxz@magog.ru</EMAIL>
	</ENTRY>
</ADDRBOOK>
